engine:
  type: "in_memory"
network:
  address: "127.0.0.1:3223"
  max_connections: 100
  max_message_size: "4KB"
  idle_timeout: 5m
logging:
  level: "info"
  output: "stdout"
  wal:
  enabled: true
  flushing_batch_size: 100
  flushing_batch_timeout: "10ms"
  max_segment_size: "10MB"
  data_directory: "/data/wal"
replication:
  enabled: true
  replica_type: "master"  # или "slave"
  master_address: "127.0.0.1:3232"
  sync_interval: "1s"